name: PlatformIO Dependabot

on:
  workflow_dispatch: # option to manually trigger the workflow
  schedule:
    # Runs every Saturday at 18:00
    - cron: '0 18 * * 6'

jobs:
  dependabot:
    runs-on: ubuntu-latest
    name: run PlatformIO Dependabot
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: run PlatformIO Dependabot
        uses: peterus/platformio_dependabot@main
        with:
          github_token: ${{ secrets.GH_PAT }}
          assignee: oleksiikutuzov
